dic = {}
name=input("What is the user's name? ")
age= input("What is the user's age? ")
country = input("What is the user's country of birth? ")
knowledge = input("What is the user known for? ")
dic['name'] = name
dic['age'] = int(age)
dic['country'] = country
dic['knowledge'] = knowledge
